export const SET_CURRENT_VIDEO = "SET_CURRENT_VIDEO";
export const START_GET_VIDEOS = "START_GET_VIDEOS";
export const END_GET_VIDEOS = "END_GET_VIDEOS";
export const SUCCESS_GET_VIDEOS = "SUCCESS_GET_VIDEOS";
export const CHANGE_PAGE = "CHANGE_PAGE";
